### PR TITLE
Add @pydanny to the Cookiecutter feedstock

### PR DESCRIPTION
**Pull request by pydanny**

### CODE REVIEW

**Comment by willingc** [comment]
@bollwyvl Would you mind merging @pydanny's pr? Thanks!

**Comment by bollwyvl** [comment]
Yeah, let's figure out the whichcraft story (which is odd, as it worked, once!), then re-kick all these... I don't think i can kick appveyor, though.

**Comment by bollwyvl** [comment]
Trigger build on whichcraft (and adding @pydanny):
https://github.com/conda-forge/whichcraft-feedstock/pull/2

**Comment by bollwyvl** [comment]
Hooray, first partial success on windows:
https://ci.appveyor.com/project/conda-forge/cookiecutter-feedstock/build/1.0.4

**Comment by willingc** [comment]
Rock on @bollwyvl 🎸  Thank you!

**Comment by bollwyvl** [comment]
@willingc thanks for the gentle prodding!

**Comment by willingc** [comment]
Happy to see @audreyr's awesome cookiecutter project over here. @bollwyvl, Both you and @pydanny are 👍  in my book. It made me happy to see both names in the same file. It's the little things that make me happy 🌻

**Comment by bollwyvl** [comment]
Yeah. Right on!

So we have the first of the jupyter cookiecutters (we should PR that):
https://github.com/jupyter/widget-cookiecutter/

I think we'll end up with more, as well.

One thing i have been thinking about is notebook enabling cookiecutter, either as a separate project or in mainline (without the notebook dep).

Basically, if we had a second json file that provided the context of the cookiecutter.json, perhaps as JSON schema (because standards :cake:) or JSON-LD context, yaml, we could create lovely, in-browser GUIs for the cookiecutter command (thinking widgets here).

Will mull over this this weekend!

**Comment by pydanny** [comment]
Awesome! Project Jupyter has its first cookiecutter!

**Pull request merged**
