### PR TITLE
Actually build 1.5.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Whoops, removed the selector, should have removed the whole line!

### CODE REVIEW

**Comment by bollwyvl** [comment]
@Cadair, sorry about that!

**Comment by Cadair** [comment]
never `skip: True` ;)

**Comment by bollwyvl** [comment]
Hm, currently `pytest-mock` is pinned to `1.1`... trying with the most recent...

**Comment by bollwyvl** [comment]
Builds locally (should totally set that up as a default pre-publish hook) with 3.6 and the unpinned pytest-mock. Also updated to smithy `2.0.1`!

**Pull request closed without merging**
