### PR TITLE
Update to 1.5.0

### PR DESCRIPTION
**Pull request by Cadair**
I did this blind on github so it might not work!

### CODE REVIEW

**Comment by bollwyvl** [comment]
Ah, `whichcraft` is us, too :) Working on a PR of that...

**Comment by bollwyvl** [comment]
> `whichcraft`

Nope, I'm totally crazy, never mind. Looking into the Circle fail...

**Comment by jakirkham** [comment]
Just saw you guys working on this. The failure is caused by this [line]( https://github.com/conda-forge/cookiecutter-feedstock/blob/a85e80ab00b705c45480b519068a1b4a3e781de9/recipe/meta.yaml#L50 ). `SRC_DIR` does not exist during testing. Instead one must use [`source_files`]( http://conda.pydata.org/docs/building/meta-yaml.html#source-files ).

**Comment by jakirkham** [comment]
Should add this is a change in `conda-build` 2.1.x.

**Comment by bollwyvl** [comment]
Yeah, sort of as expected, the 3.6 builds failed, as probably none of the upstreams have been rebuilt. I guess at this moment, we just turn off that excursion in the CI files?

**Comment by bollwyvl** [comment]
Ha, no `py36` selector yet! Probably just need to start the process of getting all the deps built... I'll link back here as I try them!

**Comment by bollwyvl** [comment]
Presently waiting on:
- conda-forge/jinja2-time-feedstock#7  (now that freezgun py3.6 is up)
- conda-forge/click-feedstock#4 (waiting for merge, with 6.6 or 6.7)

**Comment by bollwyvl** [comment]
Great, all the upstreams are ready to go (just merged jinja2-time). Need to fix up the py36 selector, then we're good to go!

**Comment by bollwyvl** [comment]
Thanks!

**Comment by Cadair** [comment]
Thank you!

**Pull request merged**
